import { defaultEditorLocalization } from 'js-draw';
import type { EditorLocalization } from 'js-draw';

type Key =
	| 'upload'
	| 'confirm'
	| 'download_your_sign'
	| 'back'
	| 'pick_locale'
	| 'zoom_instruction'
	| 'hello'
	| 'error'
	| 'failed_to_upload';
type ExpandedLocalization = EditorLocalization & Record<Key, string>;

const zh: ExpandedLocalization = {
	upload: '上傳',
	confirm: '確定上傳?',
	hello: '哈囉',
	download_your_sign: '下載你的招牌！',
	back: '回上頁',
	pick_locale: '請選擇語言',
	zoom_instruction: '使用兩根手指頭進行縮放',
	failed_to_upload: '上傳失敗',
	error: '錯誤',
	...defaultEditorLocalization,
	help: '幫助',
	helpHidden: '幫助已隱藏',
	next: '下一步',
	previous: '上一步',
	close: '關閉',
	helpScreenNavigationHelp: '點擊控件以獲取更多信息。',
	pen: '筆',
	eraser: '橡皮擦',
	select: '選擇',
	handTool: '平移',
	zoom: '縮放',
	image: '圖片',
	reformatSelection: '格式化選擇',
	inputAltText: '替代文字',
	decreaseImageSize: '減小尺寸',
	resetImage: '重置',
	chooseFile: '選擇檔案',
	dragAndDropHereOrBrowse: '拖放至此或\n{{browse}}',
	submit: '提交',
	addAll: '添加全部',
	cancel: '取消',
	resetView: '重置視圖',
	thicknessLabel: '厚度',
	colorLabel: '顏色',
	fontLabel: '字體',
	textSize: '大小',
	resizeImageToSelection: '將圖像調整為選擇區域',
	deleteSelection: '刪除選擇',
	duplicateSelection: '複製選擇',
	exit: '退出',
	save: '保存',
	undo: '撤銷',
	redo: '重做',
	fullStrokeEraser: '整筆擦除',
	selectPenType: '筆類型',
	selectShape: '形狀',
	pickColorFromScreen: '從屏幕選擇顏色',
	clickToPickColorAnnouncement: '點擊屏幕選擇顏色',
	colorSelectionCanceledAnnouncement: '顏色選擇已取消',
	selectionToolKeyboardShortcuts: '選擇工具：使用箭頭鍵移動選定項目，小寫/大寫‘i’和‘o’調整大小。',
	documentProperties: '頁面',
	backgroundColor: '背景顏色',
	imageWidthOption: '寬度',
	imageHeightOption: '高度',
	useGridOption: '網格',
	enableAutoresizeOption: '自動調整大小',
	toggleOverflow: '更多',
	about: '關於',
	inputStabilization: '穩定化',
	strokeAutocorrect: '自動校正',
	touchPanning: '觸摸平移',
	roundedTipPen: '圓頭',
	roundedTipPen2: '多邊形線',
	flatTipPen: '平頭',
	arrowPen: '箭頭',
	linePen: '線條',
	outlinedRectanglePen: '描邊矩形',
	filledRectanglePen: '填充矩形',
	outlinedCirclePen: '描邊圓形',
	lockRotation: '鎖定旋轉',
	paste: '貼上',
	errorImageHasZeroSize: '錯誤：圖像大小為零',
	describeTheImage: '圖片描述',
	fileInput__loading: '加載中...',
	penDropdown__baseHelpText: '此工具用於繪製形狀或手繪線條。',
	penDropdown__colorHelpText: '更改筆的顏色',
	penDropdown__thicknessHelpText: '更改筆劃的厚度。',
	penDropdown__penTypeHelpText:
		'更改筆的樣式。\n\n可以選擇“筆”樣式或“形狀”。選擇“筆”樣式繪製手繪線條。選擇“形狀”繪製形狀。',
	penDropdown__autocorrectHelpText:
		'將近似手繪線條和矩形轉換為完美形狀。\n\n筆在筆劃結束時保持不動以觸發校正。',
	penDropdown__stabilizationHelpText:
		'繪製更平滑的筆劃。\n\n這也會在鼠標/觸控筆和筆劃之間添加短暫延遲。',
	handDropdown__baseHelpText: '此工具負責滾動、旋轉和縮放編輯器。',
	handDropdown__zoomInHelpText: '放大。',
	handDropdown__zoomOutHelpText: '縮小。',
	handDropdown__resetViewHelpText: '將縮放級別重置為100%並重置滾動。',
	handDropdown__zoomDisplayHelpText: '顯示當前縮放級別。100%顯示圖像的實際大小。',
	handDropdown__touchPanningHelpText: '啟用時，觸摸手勢移動圖像而不是選擇或繪製。',
	handDropdown__lockRotationHelpText: '啟用時，防止觸摸手勢旋轉屏幕。',
	eraserDropdown__baseHelpText: '此工具刪除光標下的筆劃、圖片和文字。',
	eraserDropdown__thicknessHelpText: '更改橡皮擦的大小。',
	eraserDropdown__fullStrokeEraserHelpText:
		'在整筆模式下，整個形狀被擦除。\n\n不在整筆模式時，可以部分擦除形狀。',
	selectionDropdown__baseHelpText: '選擇內容並操控選擇',
	selectionDropdown__resizeToHelpText:
		'將繪圖裁剪為當前選擇的大小。\n\n如果啟用了自動調整大小，將被禁用。',
	selectionDropdown__deleteHelpText: '刪除選定項目。',
	selectionDropdown__duplicateHelpText: '複製選定項目。',
	selectionDropdown__changeColorHelpText: '更改選定項目的顏色。',
	pageDropdown__baseHelpText: '控制繪圖畫布的背景顏色、圖案和大小。',
	pageDropdown__backgroundColorHelpText: '更改繪圖畫布的背景顏色。',
	pageDropdown__gridCheckboxHelpText: '啟用/禁用背景網格圖案。',
	pageDropdown__autoresizeCheckboxHelpText:
		'選中時，頁面會隨繪圖增長。\n\n未選中時，頁面可見並可手動設置大小。',
	pageDropdown__aboutButtonHelpText: '顯示版本、調試和其他信息。',
	colorPickerPipetteHelpText: '從屏幕選擇顏色。',
	colorPickerToggleHelpText: '打開/關閉顏色選擇器。',
	selectionTool: '選擇工具',
	selectAllTool: '全選快捷鍵',
	eraserTool: '橡皮擦',
	touchPanTool: '觸摸平移',
	twoFingerPanZoomTool: '平移和縮放',
	undoRedoTool: '撤銷/重做',
	rightClickDragPanTool: '右鍵拖動平移',
	pipetteTool: '從屏幕選擇顏色',
	keyboardPanZoom: '鍵盤平移/縮放快捷鍵',
	selectionMenu__show: '顯示選擇菜單',
	selectionMenu__copyToClipboard: '複製到剪貼板',
	selectionMenu__duplicate: '複製',
	selectionMenu__delete: '刪除',
	selectionMenu__paste: '貼上',
	copyPasteError__heading: '錯誤！',
	copyPasteError__description: '出現問題——此工具可能無法訪問剪貼板。',
	copyPasteError__errorDetails: '顯示錯誤',
	copyPasteError__pasteRetry: '要重試，請將內容粘貼到下面的輸入框中：',
	autocorrectionCanceled: '自動校正已取消',
	textTool: '文字',
	enterTextToInsert: '輸入要插入的文字',
	changeTool: '更換工具',
	pasteHandler: '複製粘貼處理器',
	soundExplorer: '基於聲音的圖像探索',
	disableAccessibilityExploreTool: '禁用聲音探索',
	enableAccessibilityExploreTool: '啟用聲音探索',
	soundExplorerUsageAnnouncement:
		'啟用基於聲音的圖像探索：單擊/拖動屏幕以播放圖像不同部分的聲音表示。',
	findLabel: '查找',
	toNextMatch: '下一個',
	closeDialog: '關閉',
	findDialogShown: '查找對話框已顯示',
	findDialogHidden: '查找對話框已隱藏',
	anyDevicePanning: '任何設備平移',
	updatedViewport: '已更新視口',
	enabledAutoresizeOutputCommand: '啟用輸出自動調整大小',
	disabledAutoresizeOutputCommand: '禁用輸出自動調整大小',
	elements: '元素',
	erasedNoElements: '未擦除任何元素',
	duplicatedNoElements: '未複製任何元素',
	movedLeft: '向左移動',
	movedUp: '向上移動',
	movedDown: '向下移動',
	movedRight: '向右移動',
	zoomedOut: '縮小',
	zoomedIn: '放大',
	unlabeledImageNode: '未標記的圖像',
	stroke: '筆劃',
	svgObject: 'SVG 對象',
	emptyBackground: '空背景',
	gridBackground: '網格背景',
	rerenderAsText: '重新渲染為文本',
	accessibilityInputInstructions:
		'按“t”讀取視口內容為文本。使用箭頭鍵移動視口，單擊並拖動以繪製筆劃。按“w”放大，按“s”縮小。',
	imageEditor: '圖像編輯器',
	doneLoading: '加載完成',
	softwareLibraries: '庫',
	developerInformation: '開發者信息'
};

const en: ExpandedLocalization = {
	upload: 'upload',
	confirm: 'Are you sure?',
	download_your_sign: 'Download your sign!',
	back: 'Start over',
	pick_locale: 'Pick a language',
	zoom_instruction: 'You can you double finger to zoom in/out',
	hello: 'Hello',
	failed_to_upload: 'Failed to upload',
	error: 'Error',
	...defaultEditorLocalization
};

const localizations = { en, 'zh-tw': zh };

export { localizations };
